### ISSUE TITLE
Ratatui

### ISSUE THREAD

**Issue by joshka** [tu500/pavucontrolrs#3]
Hey there - tui-rs is no longer maintained and was forked a year ago to become [Ratatui](https://ratatui.rs). Come check us out...

![demo](https://github.com/ratatui-org/ratatui/raw/1d39444e3dea6f309cf9035be2417ac711c1abc9/examples/demo2-destroy.gif?raw=true)

- Website: https://ratatui.rs
- Crate: https://crates.io/crates/ratatui/
- Docs: https://docs.rs/ratatui/0.26.0/ratatui/
- Repo: https://github.com/ratatui-org/ratatui
- Discord: https://discord.gg/pMCEU9hNEj
- [BREAKING-CHANGES](https://github.com/ratatui-org/ratatui/blob/main/BREAKING-CHANGES.md) doc.

The two main changes that hit almost every tui-rs app is `Frame<B>` becomes `Frame`, and `Spans` becomes `Line`. Feel free to reach out on the discord channel or issues / discussions if you run into any troubles porting your app.

**Comment by tu500** [comment]
Fixed in  aba94a758ce26ebbbf606ba8a076912b2913b905.
